services:
  frontend:
    #for running locally:
    build:
      context: ./frontend
    #for hosting
    #image: makciiregistry.azurecr.io/frontend
    container_name: frontend
    environment:
      - REACT_APP_SPRING_URL=http://http://localhost:81//spring
    depends_on:
      - spring-backend
    restart: always
   
  scraping-script:
    #for running locally:
    build:
      context: ./db_init/scraping
    #for hosting
    #image: makciiregistry.azurecr.io/scraping-script:latest
    container_name: python-scraper
    environment: 
      - DB_CONNECTION_STRING=postgresql+psycopg2://sa:p123@postgres:5432/Makcii_DB
    depends_on:
      - postgres
    restart: on-failure
  
  fastapi-backend:
    #for running locally
    build:
      context: ./fastapi_backend
    #image: makciiregistry.azurecr.io/fastapi-backend:latest
    container_name: fastapi-backend
    environment:
      - DB_CONNECTION_STRING=postgresql+psycopg2://sa:p123@postgres:5432/Makcii_DB
    depends_on:
      - postgres
    restart: always
    
  microservice:
    #for running locally:
    build:
      context: ./microservice_day_data
    #for hosting
    #image: makciiregistry.azurecr.io/microservice:latest
    container_name: microservice
    environment:
      - DB_CONNECTION_STRING=jdbc:postgresql://postgres:5432/Makcii_DB
      - DB_USERNAME=sa
      - DB_PASSWORD=p123
      - PORT=8081
    depends_on:
      - postgres
    restart: always

  spring-backend:
    #for running locally:
    build:
      context: ./spring_backend
    #for hosting
    #image: makciiregistry.azurecr.io/spring-backend:latest
    container_name: spring-backend
    environment:
      - DB_CONNECTION_STRING=jdbc:postgresql://postgres:5432/Makcii_DB
      - DB_USERNAME=sa
      - DB_PASSWORD=p123
      - PORT=8080
      - FASTAPI_URL=http://fastapi-backend:8000/predict
      - MICROSERVICE_URL=http://microservice:8081/dayData/microservice
    depends_on:
      - postgres
      - microservice
      - fastapi-backend
    restart: always
      
  postgres:
    #for running locally:
    build:
      context: ./db_init
    #for hosting
    #image: makciiregistry.azurecr.io/postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: p123
      POSTGRES_DB: Makcii_DB
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "sa", "-d", "Makcii_DB"]
      interval: 10s
      retries: 5
      start_period: 60s
      timeout: 5s
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nginx:
    #for running locally:
    build:
      context: ./nginx_config
    #for hosting
    #image: makciiregistry.azurecr.io/nginx-reverse-proxy:latest
    container_name: nginx-reverse-proxy
    ports:
      - "81:80"
    depends_on:
      - frontend
      - spring-backend
      - fastapi-backend
      - microservice
    restart: always
    
    
volumes:
  postgres_data: